// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $create_list from "./islands/create-list.tsx";
import * as $fortune_wheel from "./islands/fortune-wheel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/create-list.tsx": $create_list,
    "./islands/fortune-wheel.tsx": $fortune_wheel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
